### ISSUE TITLE
warning messages

### ISSUE THREAD

**Issue by Stan92** [robertofrontado/RxSocialConnect-iOS#3]
Hi,
I'm trying to use your library (thanks by the way) and I get some warnings messages
Result of call to 'subscribe(onNext:onError:onCompleted:onDisposed:) is unused..

How can turn these messages off?
Thanks

**Comment by robertofrontado** [comment]
Hello @Stan92 ,

There are 2 ways to avoid that warning message,

First is to use `.addDisposableTo(disposeBag)`:

``` swift
RxSocialConnect.with(self, providerOAuth20: facebookApi20)
            .subscribeNext { credential in self.showAlert(credential.oauth_token) }
            .addDisposableTo(disposeBag)
```

And the other is assign that `Disposable` instance to a variable, like this:

``` swift
let _ = RxSocialConnect.with(self, providerOAuth20: facebookApi20)
            .subscribeNext { credential in self.showAlert(credential.oauth_token) }
```

**Comment by Stan92** [comment]
Hi Roberto..
Thanks your quick feedback..
Sorry for my ignorance, but I can't figure out how to translate your example with your syntax

```
    RxSocialConnect.with(self, providerOAuth20: facebookApi20)
        .subscribe(onNext: { credential in
            self.showResponse(credential)
            self.facebookApiMoya.getMe()
                .subscribe(onNext: { (response) -> Void in
                    print(NSString(data: response.data, encoding: NSUTF8StringEncoding))
                    },
                    onError: { self.showError($0 as NSError) })
            },
                   onError: { self.showError($0 as NSError) })
```

By the way, it should be my last question :)

Using the same code, I get this error
There is no active token for the provider requested
Optional({"error":{"message":"An active access token must be used to query information about the current user.","type":"OAuthException","code":2500,"fbtrace_id":"CI4XuJKKPuQ"}})

But in fact, I get the token from your showAlert.

To be more concise, I use your FacebookApiMoya file sample
I don't know if it is due to the FB API version.. but I'll try to investigate..
Anyway I thank you once again for your library, it's very helpful.

**Comment by robertofrontado** [comment]
@Stan92 Don't worry!

What specifically don't you understand of the syntax? I'll be more than glad to explain it to you,

Besides that, I should be the one thanking you for using this library, and most important showing me that it had a bug with the token (memory layer persistence), I've just released a new version `0.0.7` with that problem solved, you should try it! 

Tell me if it works now 👍

**Comment by Stan92** [comment]
You are the man... Thanks.... :-)
My bad for the misunderstand syntax, I get it..... I m getting older... :-)

**Comment by robertofrontado** [comment]
@Stan92 Perfect!

Hahaha we all are, if you need anything else don't hesitate to tell me 👍
