### ISSUE TITLE
FB example

### ISSUE THREAD

**Issue by Stan92** [robertofrontado/RxSocialConnect-iOS#8]
Hi,
Not a bug :-) 
But I think within your sample using Moya, you should replace

```
 public var parameterEncoding: Moya.ParameterEncoding {
        switch(self) {
        case .Me:
            return .JSON
        }
    }

```

by

```
 public var parameterEncoding: Moya.ParameterEncoding {
        switch(self) {
        case .Me:
            return .URL
        }
    }
```

In fact if you add parameters to get additional fields like picture, email, etc... it doesn't work using JSON as parameterEncoding..

Regards...

**Comment by robertofrontado** [comment]
Hello @Stan92,

You're right, that probably would be better, because the FB Api works with `.URL` instead of `.JSON`,

It's already done in the last [commit](https://github.com/robertofrontado/RxSocialConnect-iOS/commit/0a258e9f54cccc32400e5267c7503f236bb42e10)

Thanks!
